title:             jz.io blog
email:             your-email@example.com
description:       A Blog Theme by jz
author:            jz
brand:             jz.io
baseurl:           "/jzio-clean-blog-jekyll"
url:               "http://jz.io"

# Social Profiles
twitter_username:  justinzollars
github_username:   fogonthedowns

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
